# Memory & GC optimization
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+UseParallelGC -Dfile.encoding=UTF-8

# AndroidX & Jetifier
android.useAndroidX=true
android.enableJetifier=true

# Performance & Multithreading
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# Flutter / AGP Compatibility Flags
android.builtInKotlin=false
android.newDsl=false

# Kotlin compiler stability flags
kotlin.build.report.enable=false
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process